server:
  servlet:
    context-path: /api/v1.0

spring:
  application:
    name: authify

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
#    default-encoding: UTF-8
    properties:
      mail:
#        mime:
#          charset: UTF
        smtp:
#          writetimeout: 10000
#          connectiontimeout: 10000
#          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MY_SQL_HOST}:${MY_SQL_PORT}/${MY_SQL_DB}?createDatabaseIfNotExist=true
    username: ${MY_SQL_USERNAME}
    password: ${MY_SQL_PASSWORD}

  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update

  jwt:
    secret:
      key: thisisthesecretkeyiscreatedfordevelopmentonlyjvosjpoepksdaregerknoejoojoapdjojkdsafcsdfesrgfewrgvsgergvsesdfe






